name: ipyelk

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - bqplot >=0.12.20
  - importnb
  - ipython >=7
  - ipywidgets >=7.5.1
  - jupyterlab >=3,<4
  - jupyterlab_widgets >=1.0.0
  - networkx
  - nodejs >=14,<15
  - pandas
  - pydantic >=1
  - python >=3.7
