channels:
  - conda-forge
  - nodefaults
dependencies:
  # runtimes
  - python >=3.7,<3.12.0a0
  - jupyterlab >=3,<4
  - ipykernel !=6.19.0,!=6.19.1,!=6.19.2,!=6.19.3
  # real deps
  - ipywidgets >=8.0.4,<9
  - networkx
  - pydantic >=1
  # build
  - doit
  - flit >=3.7.1,<4
  - keyring
  - nodejs >=18,<19
  - pip
  - tomli
  - twine
  - wheel
  - packaging <22
  - pytoolconfig <1.2.4
  # demo
  - bqplot >=0.12.20
  - importnb
  - ipython >=7
  - jupyterlab-deck
  - jupyterlab-myst
  - pandas
  # lint
  - black-jupyter
  - isort
  - mypy
  - pyflakes
  - rope
  # utest
  - hypothesis-jsonschema
  - pytest-asyncio
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # atest
  - firefox =102
  - geckodriver
  - robotframework-pabot
  - robotframework-robocop
  - robotframework-seleniumlibrary
  - robotframework-tidy
  # docs
  - ansi2html
  - docutils >=0.19
  - myst-nb
  - pydata-sphinx-theme
  - pytest-check-links
  - requests-cache
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  # lite
  - jupyterlab-webrtc-docprovider
  - pkginfo
  - python-libarchive-c
  # this is handled by `doit lite:pip:install`
  # - pip:
  #   - jupyterlite ==0.1.0b15
